spring.application.name=PaymentService

server.port=8085

spring.datasource.url=jdbc:h2:mem:paymentdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

spring.main.allow-bean-definition-overriding=true


# Retry configuration
resilience4j.retry.instances.PaymentService.max-attempts=3
resilience4j.retry.instances.PaymentService.wait-duration=2000ms
resilience4j.retry.instances.PaymentService.enable-metrics=true
resilience4j.retry.instances.PaymentService.register-metrics=true
resilience4j.retry.metrics.enabled=true

# Eureka Client
eureka.client.serviceUrl.defaultZone=${EUREKA_URI:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

#For actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true
resilience4j.circuitbreaker.config.default.registerHealthIndicator=true



spring.kafka.bootstrap-servers=${KAFKA_URI:http://localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.template.default-topic=paymentTopic

logging.file.name=C://Users/somyagupta01/myProjects/microservices/logs/zion.log